# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'Sugarless' do
  
pod 'SnapKit'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'FBSDKLoginKit'
pod 'FBSDKCoreKit'

end
